### ISSUE TITLE
Bugs I gotta fix

### ISSUE THREAD

**Issue by garigari-kun** [garigari-kun/et#1]
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/garigari-kun/et/tmux_handler.SetTmuxSessions(0x11d2f94, 0x4, 0xc00001a105)
        /Users/keisuke_t/Dev/go/src/github.com/garigari-kun/et/tmux_handler/tmux_handler.go:39 +0x3b4
github.com/garigari-kun/et/cmd.RootCmd.func1(0xc0000c6000, 0x1373958, 0x0, 0x0)
        /Users/keisuke_t/Dev/go/src/github.com/garigari-kun/et/cmd/root.go:21 +0x59
github.com/spf13/cobra.(*Command).execute(0xc0000c6000, 0xc000012020, 0x0, 0x0, 0xc0000c6000, 0xc000012020)
        /Users/keisuke_t/Dev/go/src/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c6000, 0x1005f9f, 0xc000074058, 0x0)
        /Users/keisuke_t/Dev/go/src/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/keisuke_t/Dev/go/src/github.com/spf13/cobra/command.go:864
github.com/garigari-kun/et/cmd.Execute()
        /Users/keisuke_t/Dev/go/src/github.com/garigari-kun/et/cmd/root.go:52 +0x28
main.main()
        /Users/keisuke_t/Dev/go/src/github.com/garigari-kun/et/main.go:8 +0x20
exit status 2

```

**Comment by garigari-kun** [comment]
Fixed
